apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: first-argo-app
  namespace: argocd
spec:
  project: martino-project
  source:
    repoURL: https://github.com/
    targetRevision: HEAD
    path: argo/first-argo-app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: first-argo-app
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
